# Generated by Django 4.2.7 on 2023-11-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(default=12, max_length=50, verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
